local ada = require("resty.ada")


local assert = assert
local describe = describe
local it = it
local tostring = tostring


local same = assert.same
local equal = assert.equal
local is_nil = assert.is_nil
local is_true = assert.is_true
local is_false = assert.is_false
local is_table = assert.is_table


describe("Ada", function()
  describe("URL", function()
    describe(".parse", function()
      it("rejects invalid url", function()
        local u, err = ada.parse("<invalid>")
        is_nil(u)
        equal("invalid url", err)
      end)
      it("accepts valid url", function()
        local u, err = ada.parse("http://www.google.com/")
        is_table(u)
        is_nil(err)
      end)
    end)
    describe(".parse_with_base", function()
      it("accepts valid url", function()
        local u, err = ada.parse_with_base("/path?search#hash", "http://www.google.com")
        is_table(u)
        is_nil(err)
      end)
    end)
    describe(".idna_to_ascii", function()
      it("translates unicode domain to ascii", function()
        local u, err = ada.idna_to_ascii("www.7‑Eleven.com")
        equal("www.xn--7eleven-506c.com", u)
        is_nil(err)
      end)
    end)
    describe(".idna_to_unicode", function()
      it("translates ascii encoded domain to unicode", function()
        local u, err = ada.idna_to_unicode("www.xn--7eleven-506c.com")
        equal("www.7‐eleven.com", u)
        is_nil(err)
      end)
    end)
    describe(".can_parse", function()
      it("rejects invalid url", function()
        is_false(ada.can_parse(".com:443/Home/Privacy/Montréal"))
        is_false(ada.can_parse("<invalid>"))
      end)
      it("accepts valid url", function()
        is_true(ada.can_parse("https://www.7‑Eleven.com:443/Home/Privacy/Montréal"))
      end)
    end)
    describe(".can_parse_with_base", function()
      it("rejects invalid url", function()
        is_false(ada.can_parse_with_base("/path?search#hash", ".com:443/Home/Privacy/Montréal"))
        is_false(ada.can_parse_with_base("/path?search#hash", "<invalid>"))
        is_false(ada.can_parse_with_base("<invalid>", "http://"))
      end)
      it("accepts valid url", function()
        is_true(ada.can_parse_with_base("/path?search#hash", "http://www.google.com"))
      end)
    end)
    describe(".has_credentials", function()
      it("works", function()
        is_false(ada.has_credentials("https://www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_true(ada.has_credentials("https://foo:bar@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
      end)
    end)
    describe(".has_non_empty_username", function()
      it("works", function()
        is_false(ada.has_non_empty_username("https://www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_true(ada.has_non_empty_username("https://foo@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
      end)
    end)
    describe(".has_password", function()
      it("works", function()
        is_false(ada.has_password("https://www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_false(ada.has_password("https://foo@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_false(ada.has_password("https://foo:@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_true(ada.has_password("https://foo:bar@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
      end)
    end)
    describe(".has_non_empty_password", function()
      it("works", function()
        is_false(ada.has_non_empty_password("https://www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_false(ada.has_non_empty_password("https://foo@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_false(ada.has_non_empty_password("https://foo:@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        is_true(ada.has_non_empty_password("https://foo:bar@www.7‑Eleven.com:443/Home/Privacy/Montréal"))
      end)
    end)
    describe(".has_hostname", function()
      it("works", function()
        is_true(ada.has_hostname("https://www.7‑Eleven.com"))
        is_true(ada.has_hostname("file:///tmp/mock/path"))
        is_false(ada.has_hostname("non-spec:/.//p"))
      end)
    end)
    describe(".has_empty_hostname", function()
      it("works", function()
        is_false(ada.has_empty_hostname("https://www.7‑Eleven.com"))
        is_true(ada.has_empty_hostname("file:///tmp/mock/path"))
        is_false(ada.has_empty_hostname("non-spec:/.//p"))
      end)
    end)
    describe(".has_port", function()
      it("works", function()
        is_false(ada.has_port("https://www.foo.com:443")) -- this is expected to return false on standard port
        is_false(ada.has_port("https://www.foo.com"))
        is_true(ada.has_port("https://www.foo.com:8888"))
      end)
    end)
    describe(".has_search", function()
      it("works", function()
        is_true(ada.has_search("https://www.foo.com?foo=bar"))
        is_false(ada.has_search("https://www.foo.com"))
      end)
    end)
    describe(".has_hash", function()
      it("works", function()
        is_true(ada.has_hash("https://www.foo.com?foo=bar#abc"))
        is_true(ada.has_hash("https://www.foo.com#abc"))
        is_false(ada.has_hash("https://www.foo.com"))
      end)
    end)
    describe(".get_components", function()
      it("works", function()
        local c = ada.get_components("https://www.7‑Eleven.com:443/Home/Privacy/Montréal")
        equal(32, c.host_end)
        equal(9, c.host_start)
        equal(33, c.pathname_start)
        equal(7, c.protocol_end)
        equal(9, c.username_end)
      end)
    end)
    describe(".get_href", function()
      it("works", function()
        local u, err = ada.get_href("https://user:pass@host:1234/path?search#hash")
        equal("https://user:pass@host:1234/path?search#hash", u)
        is_nil(err)
      end)
    end)
    describe(".get_protocol", function()
      it("works", function()
        equal("https:", ada.get_protocol("https://www.foo.com"))
        is_nil(ada.get_protocol("www.foo.com?foo=bar"))
      end)
    end)
    describe(".get_scheme_type", function()
      it("works", function()
        equal(2, ada.get_scheme_type("https://www.foo.com"))
        equal(1, ada.get_scheme_type("grpc://www.foo.com"))
        equal(0, ada.get_scheme_type("http://www.foo.com"))
        is_nil(ada.get_scheme_type("www.foo.com"))
      end)
    end)
    describe(".get_origin", function()
      it("works", function()
        equal("https://www.foo.com", ada.get_origin("https://www.foo.com/foo/bar"))
        is_nil(ada.get_origin("www.foo.com/foo/bar"))
      end)
    end)
    describe(".get_username", function()
      it("works", function()
        equal("foo", ada.get_username("https://foo:bar@www.foo.com?foo=bar"))
        equal("", ada.get_username("https://:bar@www.foo.com?foo=bar"))
        equal("", ada.get_username("https://:@www.foo.com?foo=bar"))
        equal("", ada.get_username("https://www.foo.com?foo=bar"))
      end)
    end)
    describe(".get_password", function()
      it("works", function()
        equal("bar", ada.get_password("https://foo:bar@www.foo.com?foo=bar"))
        equal("bar", ada.get_password("https://:bar@www.foo.com?foo=bar"))
        equal("", ada.get_password("https://:@www.foo.com?foo=bar"))
        equal("", ada.get_password("https://www.foo.com?foo=bar"))
      end)
    end)
    describe(".get_host", function()
      it("works", function()
        equal("www.foo.com", ada.get_host("https://foo:bar@www.foo.com?foo=bar"))
        equal("127.0.0.1", ada.get_host("https://127.0.0.1/foo/bar"))
      end)
    end)
    describe(".get_hostname", function()
      it("works", function()
        equal("www.foo.com", ada.get_hostname("https://foo:bar@www.foo.com?foo=bar"))
        equal("127.0.0.1", ada.get_hostname("https://127.0.0.1/foo/bar"))
      end)
    end)
    describe(".get_host_type", function()
      it("works", function()
        equal(0, ada.get_host_type("https://foo:bar@www.foo.com?foo=bar"))
        equal(1, ada.get_host_type("https://127.0.0.1/foo/bar"))
      end)
    end)
    describe(".get_port", function()
      it("works", function()
        equal("", ada.get_port("https://www.foo.com:443"))
        equal("", ada.get_port("https://www.foo.com"))
        equal(8888, ada.get_port("https://www.foo.com:8888"))
      end)
    end)
    describe(".get_pathname", function()
      it("works", function()
        equal("/", ada.get_pathname("https://foo:bar@www.foo.com?foo=bar"))
        equal("/foo/bar", ada.get_pathname("https://127.0.0.1/foo/bar"))
      end)
    end)
    describe(".get_search", function()
      it("works", function()
        equal("?foo=bar", ada.get_search("https://www.foo.com?foo=bar"))
        equal("?foo=bar&a=b&b=c", ada.get_search("https://www.foo.com?foo=bar&a=b&b=c"))
        equal("", ada.get_search("https://www.foo.com/"))
        equal("", ada.get_search("https://www.foo.com?"))
      end)
    end)
    describe(".get_hash", function()
      it("works", function()
        equal("#foo-bar", ada.get_hash("https://www.foo.com?foo=bar#foo-bar"))
        equal("", ada.get_hash("https://www.foo.com#"))
        equal("", ada.get_hash("https://www.foo.com"))
      end)
    end)
    describe(".set_protocol", function()
      it("works", function()
        equal("https:", ada.get_protocol("https://www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        equal("http:", ada.get_protocol("http://www.7‑Eleven.com:443/Home/Privacy/Montréal"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy/Montréal")
        is_table(u:set_protocol("http"))
        equal("http:", u:get_protocol())
        is_table(u:set_protocol("https"))
        equal("https:", u:get_protocol())
      end)
    end)
    describe(".set_username", function()
      it("works", function()
        equal("https://user@www.xn--7eleven-506c.com/Home/Privacy/Montr%C3%A9al", ada.set_username("https://www.7‑Eleven.com:443/Home/Privacy/Montréal", "user"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy/Montréal")
        is_table(u:set_username("user"))
        equal("user", u:get_username())
      end)
    end)
    describe(".set_password", function()
      it("works", function()
        equal("https://:pass@www.xn--7eleven-506c.com/Home/Privacy/Montr%C3%A9al", ada.set_password("https://www.7‑Eleven.com:443/Home/Privacy/Montréal", "pass"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy/Montréal")
        is_table(u:set_password("pass"))
        equal("pass", u:get_password())
      end)
    end)
    describe(".set_host", function()
      it("works", function()
        equal("https://example.com/Home/Privacy/Montr%C3%A9al", ada.set_host("https://www.7‑Eleven.com:443/Home/Privacy/Montréal", "example.com"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy/Montréal")
        is_table(u:set_host("example.com"))
        equal("example.com", u:get_host())
      end)
    end)
    describe(".set_hostname", function()
      it("works", function()
        equal("https://example.com/Home/Privacy/Montr%C3%A9al", ada.set_hostname("https://www.7‑Eleven.com:443/Home/Privacy/Montréal", "example.com"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy/Montréal")
        is_table(u:set_hostname("example.com"))
        equal("example.com", u:get_host())
      end)
    end)
    describe(".set_port", function()
      it("works", function()
        equal("https://www.xn--7eleven-506c.com:1234/Home/Privacy/Montr%C3%A9al", ada.set_port("https://www.7‑Eleven.com:443/Home/Privacy/Montréal", 1234))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy/Montréal")
        is_table(u:set_port(1234))
        equal(1234, u:get_port())
      end)
    end)
    describe(".set_pathname", function()
      it("works", function()
        equal("https://www.xn--7eleven-506c.com/Doge", ada.set_pathname("https://www.7‑Eleven.com:443/Home/Privacy/Montréal", "/Doge"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy")
        equal("/Home/Privacy", u:get_pathname())
        is_table(u:set_pathname("/foo/bar"))
        equal("/foo/bar", u:get_pathname())
      end)
    end)
    describe(".set_search", function()
      it("works", function()
        equal("https://www.xn--7eleven-506c.com/Home/Privacy/Montr%C3%A9al?foo=bar", ada.set_search("https://www.7‑Eleven.com:443/Home/Privacy/Montréal", "foo=bar"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy?foo=bar")
        equal("?foo=bar", u:get_search())
        is_table(u:set_search("bar=baz"))
        equal("?bar=baz", u:get_search())
      end)
    end)
    describe(".set_hash", function()
      it("works", function()
        equal("https://www.xn--7eleven-506c.com/Home/Privacy?foo=bar#bar", ada.set_hash("https://www.7‑Eleven.com:443/Home/Privacy?foo=bar#foo", "#bar"))
        local u = ada.parse("https://www.7‑Eleven.com:443/Home/Privacy?foo=bar#foo")
        equal("#foo", u:get_hash())
        is_table(u:set_hash("#bar"))
        equal("#bar", u:get_hash())
      end)
    end)
    describe(".clear_port", function()
      it("works", function()
        equal("https://www.google.com/", ada.clear_port("https://www.google.com:8888/"))
        local u = ada.parse("https://www.google.com:8888/")
        equal("https://www.google.com/", tostring(u:clear_port()))
      end)
    end)
    describe(".clear_search", function()
      it("works", function()
        equal("https://www.google.com:8888/", ada.clear_search("https://www.google.com:8888?foo=bar"))
        local u = ada.parse("https://www.google.com:8888?foo=bar")
        equal("https://www.google.com:8888/", tostring(u:clear_search()))
      end)
    end)
    describe(".clear_hash", function()
      it("works", function()
        equal("https://www.google.com:8888/?foo=bar", ada.clear_hash("https://www.google.com:8888?foo=bar#bar"))
        local u = ada.parse("https://www.google.com:8888?foo=bar#bar")
        equal("https://www.google.com:8888/?foo=bar", tostring(u:clear_hash()))
      end)
    end)
    describe(".search_parse", function()
      it("works", function()
        local s = ada.search_parse("https://www.google.com?doge=z&jack=2")
        is_table(s)
        equal("doge=z&jack=2", s:tostring())
      end)
    end)
    describe(".search_has", function()
      it("works", function()
        is_true(ada.search_has("https://www.google.com?doge=z&jack=2", "jack"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2")
        is_true(u:search_has("jack"))
      end)
    end)
    describe(".search_has_value", function()
      it("works", function()
        is_false(ada.search_has_value("https://www.google.com?doge=z&jack=2", "jack", "4"))
        is_true(ada.search_has_value("https://www.google.com?doge=z&jack=2", "jack", "2"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2")
        is_false(u:search_has_value("jack", "4"))
        is_true(u:search_has_value("jack", "2"))
      end)
    end)
    describe(".search_get", function()
      it("works", function()
        equal("2", ada.search_get("https://www.google.com?doge=z&jack=2", "jack"))
        is_nil(ada.search_get("https://www.google.com?doge=z&jack=2", "foo"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2")
        equal("2", u:search_get("jack"))
        is_nil(u:search_get("foo"))
      end)
    end)
    describe(".search_get_all", function()
      it("works", function()
        same({}, ada.search_get_all("https://www.google.com?doge=z&jack=2&doge=s", "missing"))
        same({"z", "s"}, ada.search_get_all("https://www.google.com?doge=z&jack=2&doge=s", "doge"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2&doge=s")
        same({"z", "s"}, u:search_get_all("doge"))
      end)
    end)
    describe(".search_set", function()
      it("works", function()
        equal("https://www.google.com/?doge=z&jack=4", ada.search_set("https://www.google.com?doge=z&jack=2", "jack", "4"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2")
        equal("https://www.google.com/?doge=z&jack=4", tostring(u:search_set("jack", "4")))
      end)
    end)
    describe(".search_append", function()
      it("works", function()
        equal("https://www.google.com/?doge=z&jack=2&doge=z", ada.search_append("https://www.google.com?doge=z&jack=2", "doge", "z"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2")
        equal("https://www.google.com/?doge=z&jack=2&doge=z", tostring(u:search_append("doge", "z")))
      end)
    end)
    describe(".search_remove", function()
      it("works", function()
        equal("https://www.google.com/?jack=2&bug=&aa=3", ada.search_remove("https://www.google.com?doge=z&jack=2&doge=s&bug&aa=3", "doge"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2&doge=s&bug&aa=3")
        equal("https://www.google.com/?jack=2&bug=&aa=3", tostring(u:search_remove("doge")))
      end)
    end)
    describe(".search_remove_value", function()
      it("works", function()
        equal("https://www.google.com/?doge=z&jack=2&doge=s&bug=&aa=3", ada.search_remove_value("https://www.google.com?doge=z&jack=2&doge=s&bug&aa=3", "doge", "t"))
        equal("https://www.google.com/?jack=2&doge=s&bug=&aa=3", ada.search_remove_value("https://www.google.com?doge=z&jack=2&doge=s&bug&aa=3", "doge", "z"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2&doge=s&bug&aa=3")
        equal("https://www.google.com/?doge=z&jack=2&doge=s&bug=&aa=3", tostring(u:search_remove_value("doge", "t")))
        u = ada.parse("https://www.google.com?doge=z&jack=2&doge=s&bug&aa=3")
        equal("https://www.google.com/?jack=2&doge=s&bug=&aa=3", tostring(u:search_remove_value("doge", "z")))
      end)
    end)
    describe(".search_each", function()
      it("works", function()
        local args = {
          doge = true,
          jack = true,
          bug = true,
          aa = true,
          bb = true,
        }

        for t in ada.search_each("https://www.google.com?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[t.key])
        end

        for t in ada.search.each("?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[t.key])
        end
      end)
    end)
    describe(".search_each_key", function()
      it("works", function()
        local args = {
          doge = true,
          jack = true,
          bug = true,
          aa = true,
          bb = true,
        }

        for k in ada.search_each_key("https://www.google.com?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[k])
        end

        for k in ada.search.each_key("?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[k])
        end
      end)
    end)
    describe(".search_each_value", function()
      it("works", function()
        local args = {
          z = true,
          ["2"] = true,
          s = true,
          [""] = true,
          ["3"] = true,
          ["4"] = true,
          ["10"] = true,
        }

        for v in ada.search_each_value("https://www.google.com?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[v])
        end

        for v in ada.search.each_value("?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[v])
        end
      end)
    end)
    describe(".search_pairs", function()
      it("works", function()
        local args = {
          doge = true,
          jack = true,
          bug = true,
          aa = true,
          bb = true,
        }

        for k in ada.search_pairs("https://www.google.com?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[k])
        end

        for k in ada.search.pairs("?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[k])
        end
      end)
    end)
    describe(".search_ipairs", function()
      it("works", function()
        local args = {
          doge = true,
          jack = true,
          bug = true,
          aa = true,
          bb = true,
        }

        for _, v in ada.search_ipairs("https://www.google.com?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[v.key])
        end

        for _, v in ada.search.ipairs("?doge=z&jack=2&doge=s&bug=&aa=3&bb=4&bb=10") do
          is_true(args[v.key])
        end
      end)
    end)
    describe(".search_sort", function()
      it("works", function()
        equal("https://www.google.com/?doge=z&doge=s&jack=2", ada.search_sort("https://www.google.com?doge=z&jack=2&doge=s"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2&doge=s")
        equal("https://www.google.com/?doge=z&doge=s&jack=2", tostring(u:search_sort()))
      end)
    end)
    describe(".search_size", function()
      it("works", function()
        equal(3, ada.search_size("https://www.google.com?doge=z&jack=2&doge=s"))
        local u = ada.parse("https://www.google.com?doge=z&jack=2&doge=s")
        equal(3, u:search_size())
      end)
    end)
  end)
end)
