name: unit-tests
on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["luajit-openresty"]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: docker build dev/ -t resty-ada

      - name: Run tests
        run: docker run --network=host -v $PWD:/test -w /test resty-ada bash -c "make test"
